### ISSUE TITLE
Bug/Glitch on Download page while downloading game

### ISSUE THREAD

**Issue by SleepDaemon** [redsigma/Unofficial-Patch-for-MetroForSteam#62]
This is what it looks like when you downloading a game, but the game image blocks the download stats.

![image](https://user-images.githubusercontent.com/88533953/168521322-49e4e592-df83-416b-ba84-346d6b2f8763.png)

![image](https://user-images.githubusercontent.com/88533953/168521429-4f10514d-d82e-49fd-bb08-10f6aa96aa1d.png)

I also notice it doesn't show the download graph.

this image was taken from the web
![image](https://cdn.neow.in/news/images/uploaded/2021/07/1627630814_steam_new_downloads.jpg)

**Comment by redsigma** [comment]
The following pages / windows, are no longer related to Metro Skin:
Library , Downloads, Friends, Game Properties

You're most likely using a library skin (it customizes the downloads page as well), so please contact the author of that skin.
