### ISSUE TITLE
missing selection button

### ISSUE THREAD

**Issue by nd002723** [redsigma/Unofficial-Patch-for-MetroForSteam#63]
for example, I cannot choose to save my password in the login screen
![IL3KBDW.png](https://s2.loli.net/2022/07/11/btr5I19RhdQzy7O.png)

**Comment by redsigma** [comment]
you did not install the **patch** correctly. The patch doesn't have all the files.

PS: You can check that button even if you're missing the image

**Comment by redsigma** [comment]
Please use this to install metro + the patch

https://github.com/henrikx/metroskininstaller/releases

Otherwise, download official metro and install this patch on top if, and replace all files when asked

**Comment by nd002723** [comment]
> Otherwise, download official metro and install this patch on top if, and replace all files when asked

replacing files really works，thx
