### ISSUE TITLE
[BUG] Strange Skinning Bug

### ISSUE THREAD

**Issue by SkyHighPurchase** [redsigma/Unofficial-Patch-for-MetroForSteam#64]
![image](https://user-images.githubusercontent.com/90104965/204867116-5bff193d-ac0e-4c8f-b157-cae3f8aebc94.png)

All of the windows are like this. The top bar has the skin, but nothing else does. (Including Store, Community, and my Profile)

**Comment by johanaxel007** [comment]
I believe that's how it should be with the current Steam versions, starting from 2019 the Steam client started using an other system (Chromium) to do the interface, breaking a lot of skins (eg: what you're seeing now).

On top of that, the new Chromium system doesn't support the build in skin system of Steam so changes to the top bar, settings menu and overlay are basically the only things supported.

I am not a developer of Steam skins so it's better to wait for an official answer from redsigma, but I believe that's the gist of it.

**Comment by redsigma** [comment]
This is not a bug. Valve is migrating steam to a web based app. This means that skinning the web is done by editing the css code. However valve doesn't offer a way to skin these new parts, but there is a way to skin these (friends, downloads, etc). 

Check this out for how to skin the library, https://github.com/PhantomGamers/SFP

**Comment by SkyHighPurchase** [comment]
Thank you all for the help.
