### ISSUE TITLE
[Feature Request] Updates available icon marker 

### ISSUE THREAD

**Issue by filibie** [redsigma/Unofficial-Patch-for-MetroForSteam#66]
Hello 👋

I would like to request a feature of a different icon when downloads are available. As of now there's no visual indication there are any new updates available. Some kind of a blue or yellow, minimalist dot addition to existing down-facing arrow when updates are available would be a very nice improvement. 

Thanks 😄

**Comment by redsigma** [comment]
From what I know there is no way to tell in the default steam if you have any pending updates. If you know something , could you post a screenshot and I'll see if i can replicate it.

**Comment by filibie** [comment]
I see, it could be tricky to implement this just as a UI theme mod if steam app doesn't expose this kind of feature by default. I guess we just need to wait for a major redesign of the official steam app UI which is very much dated at this point in my opinion   ┑(￣Д ￣)┍
