### ISSUE TITLE
log out owerlaping

### ISSUE THREAD

**Issue by Meowfuze** [redsigma/Unofficial-Patch-for-MetroForSteam#70]
![image](https://user-images.githubusercontent.com/126733218/225995243-fd7ed03c-a01c-4bdc-a14b-0f19f491aa79.png)

**Comment by slistack** [comment]
I believe this has been fixed in 57fb366 with repo fix in prep for Release 9.1.46

**Comment by redsigma** [comment]
Actually it was fixed in 50244e15e2ad49fa36266590a83cb0c2ce011fdf  but yeah, gonna close this
