### ISSUE TITLE
Friends window crashes when right clicking a friend

### ISSUE THREAD

**Issue by Raylands** [redsigma/Unofficial-Patch-for-MetroForSteam#71]
Whenever I right click a friend the friend window crashes.
This doesn't happen when I disable the skin.
Latest unoffical patch is installed. 
![image](https://user-images.githubusercontent.com/43676611/227735496-550c7393-0046-406f-862c-8452b0703eb5.png)

**Comment by redsigma** [comment]
This isnt related to metro. Metro cannot edit the new blue ui. Try to switch to steam beta and see if the problem gets fixed. I am using steam beta and I dont have this problem.
